#!/bin/bash

set -euo pipefail

USER_EXT="$HOME/.local/share/gnome-shell/extensions"
GLOBAL_EXT="/usr/share/gnome-shell/extensions"
KEYFILE="/etc/dconf/db/local.d/10-gnome-shell-extensions"

# dconf dump emits section paths relative to the dumped dir ([/], [blur-my-shell]);
# the keyfile database needs them absolute and without the leading slash.
prefix_sections() {
  sed -e 's|^\[/\]$|['"$1"']|' -e t -e 's|^\[|['"$1"'/|'
}

if [[ "${1:-}" == "--check" ]]; then
  got=$(printf '[/]\nfoo=1\n\n[blur-my-shell]\nbar=2\n' | prefix_sections org/gnome/shell/extensions)
  want=$'[org/gnome/shell/extensions]\nfoo=1\n\n[org/gnome/shell/extensions/blur-my-shell]\nbar=2'
  if [[ "$got" == "$want" ]]; then
    echo "✅ prefix_sections ok"
  else
    printf '❌ prefix_sections got:\n%s\n' "$got"
    exit 1
  fi
  exit 0
fi

# ─────────────────────────────────────────────
# Collect user extensions
# ─────────────────────────────────────────────
shopt -s nullglob
exts=("$USER_EXT"/*/)

if ((${#exts[@]} == 0)); then
  echo "ℹ️  No user extensions in $USER_EXT — nothing to do."
  exit 0
fi

echo "🌍 Moving ${#exts[@]} extension(s) to $GLOBAL_EXT"
sudo mkdir -p "$GLOBAL_EXT"

for d in "${exts[@]}"; do
  name=$(basename "$d")
  echo "→ $name"
  sudo rm -rf "${GLOBAL_EXT:?}/$name"
  sudo cp -a "$d" "$GLOBAL_EXT/$name"
done

sudo chown -R root:root "$GLOBAL_EXT"
sudo restorecon -R "$GLOBAL_EXT" 2>/dev/null || true

# ─────────────────────────────────────────────
# Export current settings as system-wide defaults
# ─────────────────────────────────────────────
echo "⚙️  Writing system defaults to $KEYFILE"

enabled=$(dconf read /org/gnome/shell/enabled-extensions)
if [[ -z "$enabled" ]]; then
  echo "⚠️  /org/gnome/shell/enabled-extensions is unset — new users will get the extensions installed but disabled."
  enabled="[]"
fi

sudo mkdir -p "$(dirname "$KEYFILE")"
{
  echo "# Generated by globalExtensions.sh on $(date -I) — do not edit by hand"
  echo
  echo "[org/gnome/shell]"
  echo "enabled-extensions=$enabled"
  echo "disable-user-extensions=false"
  echo
  dconf dump /org/gnome/shell/extensions/ | prefix_sections org/gnome/shell/extensions
} | sudo tee "$KEYFILE" > /dev/null

sudo dconf update

# ─────────────────────────────────────────────
# Drop the user copies now that the global ones exist
# ─────────────────────────────────────────────
echo "🧹 Removing user copies..."
for d in "${exts[@]}"; do
  name=$(basename "$d")
  if [[ -d "$GLOBAL_EXT/$name" ]]; then
    rm -rf "${USER_EXT:?}/$name"
  else
    echo "⚠️  $name never landed in $GLOBAL_EXT — keeping the user copy."
  fi
done

echo "✅ Done. Log out and back in (or reboot) for GNOME Shell to pick up the global extensions."
